package com.mevi.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF686CFF)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFE1E0FF)
val light_onPrimaryContainer = Color(0xFF06006C)
val light_secondary = Color(0xFF5D5C72)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFE2E0F9)
val light_onSecondaryContainer = Color(0xFF191A2C)
val light_tertiary = Color(0xFF225FA6)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFD5E3FF)
val light_onTertiaryContainer = Color(0xFF001C3B)
val light_error = Color(0xFFDC3545)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1C1B1F)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1C1B1F)
val light_surfaceVariant = Color(0xFFE4E1EC)
val light_onSurfaceVariant = Color(0xFF46464F)
val light_outline = Color(0xFF777680)
val light_inverseOnSurface = Color(0xFFF3EFF4)
val light_inverseSurface = Color(0xFF313034)
val light_inversePrimary = Color(0xFFC0C1FF)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF4649DD)
val light_outlineVariant = Color(0xFFC8C5D0)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFC0C1FF)
val dark_onPrimary = Color(0xFF382CB6)
val dark_primaryContainer = Color(0xFF2B2AC5)
val dark_onPrimaryContainer = Color(0xFFE1E0FF)
val dark_secondary = Color(0xFFC6C4DD)
val dark_onSecondary = Color(0xFF2E2F42)
val dark_secondaryContainer = Color(0xFF454559)
val dark_onSecondaryContainer = Color(0xFFE2E0F9)
val dark_tertiary = Color(0xFFA7C8FF)
val dark_onTertiary = Color(0xFF003060)
val dark_tertiaryContainer = Color(0xFF004788)
val dark_onTertiaryContainer = Color(0xFFD5E3FF)
val dark_error = Color(0xFFFDEDEE)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1C1B1F)
val dark_onBackground = Color(0xFFE5E1E6)
val dark_surface = Color(0xFF1C1B1F)
val dark_onSurface = Color(0xFFE5E1E6)
val dark_surfaceVariant = Color(0xFF46464F)
val dark_onSurfaceVariant = Color(0xFFC8C5D0)
val dark_outline = Color(0xFF918F9A)
val dark_inverseOnSurface = Color(0xFF1C1B1F)
val dark_inverseSurface = Color(0xFFE5E1E6)
val dark_inversePrimary = Color(0xFF4649DD)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFC0C1FF)
val dark_outlineVariant = Color(0xFF46464F)
val dark_scrim = Color(0xFF000000)

val seed = Color(0xFF686CFF)

val success_light = Color(0xFFECFCF0)
val success_dark = Color(0xFF28A745)
val info_box_info_light = Color(0xFFEDF6FD)
val info_box_info_dark = Color(0xFF40A3EB)
val info_box_notice_light = Color(0xFFFCF5EC)
val info_box_notice_dark = Color(0xFFFFB24E)